### ISSUE TITLE
BE 710 (IL2CPP) broke Sinai's UniverseLib based ConfigManager

### ISSUE THREAD

**Issue by p1xel8ted** [BepInEx/BepInEx#1002]
### What happened?

BE 710 broke Sinai's UniverseLib based ConfigManager, game doesn't matter.

[ConfigManager.zip](https://github.com/user-attachments/files/17266000/ConfigManager.zip)

### Steps to reproduce

1. Install any IL2CPP Unity game (most recent game I'm working on is WitchSpring R, but any should be fine)
2. Install BepInEx IL2CPP BE710+
3. Install attached ConfigManager build
4. Run game

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

**709**

```txt
[Message: Preloader] BepInEx 6.0.0-be.709 - WitchSpringR
[Message: Preloader] Built from commit 2a61b614978b1f3388c41f7784c43178ba98b58e
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.47f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   :AssemblyPatcher] Loaded 0 patcher
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 1 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin provider to load
[Info   :   BepInEx] Loading [BepInExPluginProvider 1.0.0]
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [BepInExConfigManager 1.3.0]
[Info   :Il2CppInterop] Registered mono type ConfigManager.ConfigManager+ManagerBehaviour in il2cpp domain
[Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initializing...
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[Message:BepInExConfigManager] [UniverseLib] Finished UniverseLib initial setup.
[Info   :   BepInEx] Loading [WitchSpring R Ultra-Wide 0.1.3]
```

**710+**

```txt
[Message: Preloader] BepInEx 6.0.0-be.725 - WitchSpringR (29/09/2024 10:26:20 AM)
[Message: Preloader] Built from commit e1974e26fd7702c66b54c0d6879c90b988cc4920
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.47f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   :AssemblyPatcher] Loaded 1 patcher type from [BepInExConfigManager.Il2Cpp.Patcher 1.0.0.0]
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 1 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [BepInExConfigManager 1.3.0]
[Info   :Il2CppInterop] Registered mono type ConfigManager.ConfigManager+ManagerBehaviour in il2cpp domain
[Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initializing...
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Error  :   BepInEx] Error loading [BepInExConfigManager 1.3.0]: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.BaseField`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
   at UniverseLib.ReflectionUtility.SetupTypeCache()
   at UniverseLib.ReflectionUtility.Initialize()
   at UniverseLib.Il2CppReflection.Initialize()
   at UniverseLib.ReflectionUtility.Init()
   at UniverseLib.Universe.Init(Single startupDelay, Action onInitialized, Action`2 logHandler, UniverseLibConfig config)
   at ConfigManager.ConfigManager.Init()
   at ConfigManager.ConfigManager.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 136
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
[Info   :   BepInEx] Loading [WitchSpring R Ultra-Wide 0.1.3]
```

### Environment

```markdown
- OS: Windows 11 23H2 22631.4249
- BepInEx: BE IL2CPP 710+
- Game: Any (one in logs is WitchSpring R)
```

**Comment by js6pak** [comment]
@ManlyMarco 
![image](https://github.com/user-attachments/assets/6698330a-63cb-485b-89bf-8042d537046c)

**Comment by ManlyMarco** [comment]
Which fork? I'm pretty sure some versions work fine. The bug is [here](https://github.com/sinai-dev/UniverseLib/blob/f6a9ed9a4d58bfe13eaae570c53f59a00b575ca0/src/Reflection/ReflectionUtility.cs#L122) because it assumes all types can be loaded, it should have been wrapped in a trycatch since it will crash if any assembly with unloadable types is ever loaded.

**Comment by p1xel8ted** [comment]
From here. https://github.com/Vapok/BepInExConfigManager

**Comment by ManlyMarco** [comment]
So basically vanilla, wrap the code I mentioned in a trycatch and it will work.

**Comment by p1xel8ted** [comment]
> So basically vanilla, wrap the code I mentioned in a trycatch and it will work. Not sure if there are nuget packages for the forks of UniuverseLib with the issue fixed but if there are you could just switch the reference to that.

Yeah, I use your ConfigManager for Mono games, so I just needed one that was compiled for BIE. Issue is fixed with the try catch - thanks
