### ISSUE TITLE
BepInEx 6 Idle Clans texturepack problem

### ISSUE THREAD

**Issue by Ramcin00** [BepInEx/BepInEx#1012]
### What happened?

About 4 days ago I decided to create the first full(currently supported) texture pack based on Minecraft textures for Idle Clans.
Everything worked perfectly until the first 100 or so textures were introduced, the first symptoms of problems were difficulty starting the game, a moment after showing the start-screen of Unity the game closed itself, sometimes it was related to the program hanging, sometimes not. The game started after about 3/4 of starting.
After introducing about 600 textures the game stopped launching completely regardless of the number of attempts. Deleting the texturepack from the "texturepack" folder solves the problem and the game launches normally.
BepInEx console shows nothing, last note before crashing the game:
>[Message: Unity] CustomSteamManager init

Content of **ErrorLog.log** is as follows:

> Setting breakpad minidump AppID = 2103530
> SteamInternal_SetMinidumpSteamID: Caching Steam ID: 76561198147553602 [API loaded no]
> Fatal error. 0xC0000005
> at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
> at UnityEngine.ImageConversion.LoadImage(UnityEngine.Texture2D, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1)
> at IdlePlus.TexturePack.TexturePack.CreateAtlas(System.String)
> at IdlePlus.TexturePack.TexturePack.Load()
> at IdlePlus.TexturePack.TexturePackManager+<>c__DisplayClass8_0.b__1()
> at IdlePlus.Utilities.IdleTasks+<>c__DisplayClass2_0.b__0(IdleTask)
> at IdlePlus.Utilities.IdleTasks+IdleTask.Run()
> at IdlePlus.Utilities.IdleTasks+IdleTask.Tick()
> at IdlePlus.Utilities.IdleTasks.Tick()
> at DynamicClass.Trampoline_VoidThisIdlePlus.IdlePlusBehaviourUpdate(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
> at DynamicClass.Invoker_VoidThis(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*, IntPtr, IntPtr*, IntPtr*)

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
LogOutput.log:
[Message: Preloader] BepInEx 6.0.0-be.692 - Idle Clans
[Message: Preloader] Built from commit 851521cc126e4f9d841d2d9bfe857558f0395939
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2022.3.29f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Idle Plus 1.3.0]
[Info   : Idle Plus] Loading Idle Plus v1.3.0...
[Info   : Idle Plus] Deserialized toggle setting: feature_totalWealth, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_scrollInfo, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_equipmentStatsInfo, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_maxOpenableChests, value: True
[Info   : Idle Plus] Deserialized toggle setting: ui_enhancedInventoryStats, value: True
[Info   : Idle Plus] Deserialized toggle setting: ui_enhancedInventoryItemTooltip, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_hideforim, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_shifttotal, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_includeNegotiation, value: False
[Info   : Idle Plus] Deserialized dropdown setting: marketvalue_display, value: 0
[Info   : Idle Plus] Deserialized dropdown setting: marketvalue_format, value: 0
[Info   : Idle Plus] Deserialized toggle setting: misc_internalItemNames, value: True
[Info   :Il2CppInterop] Registered mono type IdlePlus.IdlePlusBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.DebugRender in il2cpp domain
[Warning:Il2CppInterop] Method System.String[] get_Items() on type IdlePlus.Unity.IdlePlusDropdown has unsupported return type System.String[]
[Warning:Il2CppInterop] Method Void set_Items(System.String[]) on type IdlePlus.Unity.IdlePlusDropdown has unsupported parameter System.String[] value of type System.String[]
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.IdlePlusDropdown in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.HotItemButton in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.MatchParentSize in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.Items.EquipmentStatsInfo in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.Items.ScrollInfo in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.DropdownSettingsEntry in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.SettingsPopupIdlePlusTab in il2cpp domain
[Warning:Il2CppInterop] Method Void Initialize(IdlePlus.Settings.SettingCategory) on type IdlePlus.Settings.Unity.SettingsSection has unsupported parameter IdlePlus.Settings.SettingCategory category of type IdlePlus.Settings.SettingCategory
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.SettingsSection in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.ToggleSettingsEntry in il2cpp domain
[Info   : Idle Plus] Idle Plus v1.3.0 loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Idle Plus] Scene loaded: MainMenu
[Info   : Idle Plus] Duplicate game object name: LeanTransition
[Info   : Idle Plus] Cached 67 game objects in 23ms.
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Utilities.Helpers.UiHelper
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Patches.GeneralPatches
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Patches.Popups.SettingsPopupPatch
[Info   : Idle Plus] Ran InitializeOnce for scene MainMenu in 40ms
[Info   : Idle Plus] Ran Initialize on scene MainMenu for IdlePlus.Patches.Profile.ProfilePanelPatch
[Info   : Idle Plus] Ran Initialize on scene MainMenu for IdlePlus.Patches.Equipment.UIEquipmentBonusesPatch
[Info   : Idle Plus] Ran Initialize for scene MainMenu in 2ms
[Message: Preloader] BepInEx 6.0.0-be.692 - Idle Clans
[Message: Preloader] Built from commit 851521cc126e4f9d841d2d9bfe857558f0395939
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2022.3.29f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Idle Plus 1.3.0]
[Info   : Idle Plus] Loading Idle Plus v1.3.0...
[Info   : Idle Plus] Deserialized toggle setting: feature_totalWealth, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_scrollInfo, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_equipmentStatsInfo, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_maxOpenableChests, value: True
[Info   : Idle Plus] Deserialized toggle setting: ui_enhancedInventoryStats, value: True
[Info   : Idle Plus] Deserialized toggle setting: ui_enhancedInventoryItemTooltip, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_hideforim, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_shifttotal, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_includeNegotiation, value: False
[Info   : Idle Plus] Deserialized dropdown setting: marketvalue_display, value: 0
[Info   : Idle Plus] Deserialized dropdown setting: marketvalue_format, value: 0
[Info   : Idle Plus] Deserialized toggle setting: misc_internalItemNames, value: True
[Info   :Il2CppInterop] Registered mono type IdlePlus.IdlePlusBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.DebugRender in il2cpp domain
[Warning:Il2CppInterop] Method System.String[] get_Items() on type IdlePlus.Unity.IdlePlusDropdown has unsupported return type System.String[]
[Warning:Il2CppInterop] Method Void set_Items(System.String[]) on type IdlePlus.Unity.IdlePlusDropdown has unsupported parameter System.String[] value of type System.String[]
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.IdlePlusDropdown in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.HotItemButton in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.MatchParentSize in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.Items.EquipmentStatsInfo in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.Items.ScrollInfo in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.DropdownSettingsEntry in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.SettingsPopupIdlePlusTab in il2cpp domain
[Warning:Il2CppInterop] Method Void Initialize(IdlePlus.Settings.SettingCategory) on type IdlePlus.Settings.Unity.SettingsSection has unsupported parameter IdlePlus.Settings.SettingCategory category of type IdlePlus.Settings.SettingCategory
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.SettingsSection in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.ToggleSettingsEntry in il2cpp domain
[Info   : Idle Plus] Idle Plus v1.3.0 loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Idle Plus] Scene loaded: MainMenu
[Info   : Idle Plus] Duplicate game object name: LeanTransition
[Info   : Idle Plus] Cached 67 game objects in 23ms.
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Utilities.Helpers.UiHelper
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Patches.GeneralPatches
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Patches.Popups.SettingsPopupPatch
[Info   : Idle Plus] Ran InitializeOnce for scene MainMenu in 64ms
[Info   : Idle Plus] Ran Initialize on scene MainMenu for IdlePlus.Patches.Profile.ProfilePanelPatch
[Info   : Idle Plus] Ran Initialize on scene MainMenu for IdlePlus.Patches.Equipment.UIEquipmentBonusesPatch
[Info   : Idle Plus] Ran Initialize for scene MainMenu in 3ms
[Message: Preloader] BepInEx 6.0.0-be.692 - Idle Clans
[Message: Preloader] Built from commit 851521cc126e4f9d841d2d9bfe857558f0395939
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2022.3.29f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Message: Preloader] BepInEx 6.0.0-be.692 - Idle Clans
[Message: Preloader] Built from commit 851521cc126e4f9d841d2d9bfe857558f0395939
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2022.3.29f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Idle Plus 1.3.0]
[Info   : Idle Plus] Loading Idle Plus v1.3.0...
[Info   : Idle Plus] Deserialized toggle setting: feature_totalWealth, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_scrollInfo, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_equipmentStatsInfo, value: True
[Info   : Idle Plus] Deserialized toggle setting: feature_maxOpenableChests, value: True
[Info   : Idle Plus] Deserialized toggle setting: ui_enhancedInventoryStats, value: True
[Info   : Idle Plus] Deserialized toggle setting: ui_enhancedInventoryItemTooltip, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_hideforim, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_shifttotal, value: True
[Info   : Idle Plus] Deserialized toggle setting: marketvalue_includeNegotiation, value: False
[Info   : Idle Plus] Deserialized dropdown setting: marketvalue_display, value: 0
[Info   : Idle Plus] Deserialized dropdown setting: marketvalue_format, value: 0
[Info   : Idle Plus] Deserialized toggle setting: misc_internalItemNames, value: True
[Info   :Il2CppInterop] Registered mono type IdlePlus.IdlePlusBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.DebugRender in il2cpp domain
[Warning:Il2CppInterop] Method System.String[] get_Items() on type IdlePlus.Unity.IdlePlusDropdown has unsupported return type System.String[]
[Warning:Il2CppInterop] Method Void set_Items(System.String[]) on type IdlePlus.Unity.IdlePlusDropdown has unsupported parameter System.String[] value of type System.String[]
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.IdlePlusDropdown in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.HotItemButton in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.MatchParentSize in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.Items.EquipmentStatsInfo in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Unity.Items.ScrollInfo in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.DropdownSettingsEntry in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.SettingsPopupIdlePlusTab in il2cpp domain
[Warning:Il2CppInterop] Method Void Initialize(IdlePlus.Settings.SettingCategory) on type IdlePlus.Settings.Unity.SettingsSection has unsupported parameter IdlePlus.Settings.SettingCategory category of type IdlePlus.Settings.SettingCategory
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.SettingsSection in il2cpp domain
[Info   :Il2CppInterop] Registered mono type IdlePlus.Settings.Unity.ToggleSettingsEntry in il2cpp domain
[Info   : Idle Plus] Idle Plus v1.3.0 loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Idle Plus] Scene loaded: MainMenu
[Info   : Idle Plus] Duplicate game object name: LeanTransition
[Info   : Idle Plus] Cached 67 game objects in 37ms.
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Utilities.Helpers.UiHelper
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Patches.GeneralPatches
[Info   : Idle Plus] Ran InitializeOnce on scene MainMenu for IdlePlus.Patches.Popups.SettingsPopupPatch
[Info   : Idle Plus] Ran InitializeOnce for scene MainMenu in 69ms
[Info   : Idle Plus] Ran Initialize on scene MainMenu for IdlePlus.Patches.Profile.ProfilePanelPatch
[Info   : Idle Plus] Ran Initialize on scene MainMenu for IdlePlus.Patches.Equipment.UIEquipmentBonusesPatch
[Info   : Idle Plus] Ran Initialize for scene MainMenu in 6ms

ErrorLog.log:
Setting breakpad minidump AppID = 2103530
SteamInternal_SetMinidumpSteamID: Caching Steam ID: 76561198147553602 [API loaded no]
Fatal error. 0xC0000005
at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
at UnityEngine.ImageConversion.LoadImage(UnityEngine.Texture2D, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1)
at IdlePlus.TexturePack.TexturePack.CreateAtlas(System.String)
at IdlePlus.TexturePack.TexturePack.Load()
at IdlePlus.TexturePack.TexturePackManager+<>c__DisplayClass8_0.b__1()
at IdlePlus.Utilities.IdleTasks+<>c__DisplayClass2_0.b__0(IdleTask)
at IdlePlus.Utilities.IdleTasks+IdleTask.Run()
at IdlePlus.Utilities.IdleTasks+IdleTask.Tick()
at IdlePlus.Utilities.IdleTasks.Tick()
at DynamicClass.Trampoline_VoidThisIdlePlus.IdlePlusBehaviourUpdate(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
at DynamicClass.Invoker_VoidThis(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*, IntPtr, IntPtr*, IntPtr*)
```

### Environment

```markdown
- OS: Win11
- BepInEx: 6.0.0.0
- Game: Idle Clans
```

**Comment by Ramcin00** [comment]
Problem is directly related to the IdlePlus plugin, the issue is continued on the IdlePlus repo
