### ISSUE TITLE
When running Steam Game Aska, it does not run BenpinEx.

### ISSUE THREAD

**Issue by redmong80** [BepInEx/BepInEx#1013]
### What happened?

It worked fine until November 4th, 24, but it doesn't work on November 6th.

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.725 - Aska (2024-11-03 오후 8:02:54)
[Message: Preloader] Built from commit e1974e26fd7702c66b54c0d6879c90b988cc4920
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.48f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.4.0]
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.1.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :XUnity.AutoTranslator] Force loading ALL proxy assemblies.
[Error  :Il2CppInterop] Nested type ToolbarButtonSize on GUI not found!
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.GUI+ToolbarButtonSize
System.ArgumentException: ToolbarButtonSize does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray<int>, int, int)
[Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
[Error  :XUnity.AutoTranslator] The specified override font is not available. Available fonts: Agency FB, Agency FB Bold, Algerian, Ami R, Arial, Arial Bold, Arial Italic, Arial Bold Italic, Arial Rounded MT Bold, Arial Unicode MS, Bahnschrift, Baskerville Old Face, Batang, BatangChe, Bauhaus 93, Bell MT, Bell MT Bold, Bell MT Italic, Berlin Sans FB, Berlin Sans FB Bold, Berlin Sans FB Demi Bold, Bernard MT Condensed, Blackadder ITC, Bodoni MT, Bodoni MT Bold, Bodoni MT Italic, Bodoni MT Bold Italic, Book Antiqua, Book Antiqua Bold, Book Antiqua Italic, Book Antiqua Bold Italic, Bookman Old Style, Bookman Old Style Bold, Bookman Old Style Italic, Bookman Old Style Bold Italic, Bookshelf Symbol 7, Bradley Hand ITC, Britannic Bold, Broadway, Brush Script MT Italic, Calibri, Calibri Bold, Calibri Italic, Calibri Bold Italic, Californian FB, Californian FB Bold, Californian FB Italic, Calisto MT, Calisto MT Bold, Calisto MT Italic, Calisto MT Bold Italic, Cambria, Cambria Bold, Cambria Italic, Cambria Bold Italic, Cambria Math, Candara, Candara Bold, Candara Italic, Candara Bold Italic, Castellar, Centaur, Century, Century Gothic, Century Gothic Bold, Century Gothic Italic, Century Gothic Bold Italic, Century Schoolbook, Century Schoolbook Bold, Century Schoolbook Italic, Century Schoolbook Bold Italic, Chiller, Colonna MT, Comic Sans MS, Comic Sans MS Bold, Comic Sans MS Italic, Comic Sans MS Bold Italic, Consolas, Consolas Bold, Consolas Italic, Consolas Bold Italic, Constantia, Constantia Bold, Constantia Italic, Constantia Bold Italic, Cooper Black, Copperplate Gothic Bold, Copperplate Gothic Light, Corbel, Corbel Bold, Corbel Italic, Corbel Bold Italic, Courier New, Courier New Bold, Courier New Italic, Courier New Bold Italic, Curlz MT, Dotum, DotumChe, Ebrima, Ebrima Bold, Edwardian Script ITC, Elephant, Elephant Italic, Engravers MT, Eras Bold ITC, Eras Demi ITC, Eras Light ITC, Eras Medium ITC, Expo M, Felix Titling, Footlight MT Light, Forte, Franklin Gothic Book, Franklin Gothic Book Italic, Franklin Gothic Demi, Franklin Gothic Demi Italic, Franklin Gothic Demi Cond, Franklin Gothic Heavy, Franklin Gothic Heavy Italic, Franklin Gothic Medium, Franklin Gothic Medium Italic, Franklin Gothic Medium Cond, Freestyle Script, French Script MT, Gabriola, Gadugi, Gadugi Bold, Garamond, Garamond Bold, Garamond Italic, Georgia, Georgia Bold, Georgia Italic, Georgia Bold Italic, Gigi, Gill Sans MT, Gill Sans MT Bold, Gill Sans MT Italic, Gill Sans MT Bold Italic, Gill Sans MT Condensed, Gill Sans MT Ext Condensed Bold, Gill Sans Ultra Bold, Gill Sans Ultra Bold Condensed, Gloucester MT Extra Condensed, Goudy Old Style, Goudy Old Style Bold, Goudy Old Style Italic, Goudy Stout, Gulim, GulimChe, Gungsuh, GungsuhChe, HYGothic-Extra, HYGothic-Medium, HYGraphic-Medium, HYGungSo-Bold, HYHeadLine-Medium, HYMyeongJo-Extra, HYPMokGak-Bold, HYPost-Light, HYPost-Medium, HYShortSamul-Medium, HYSinMyeongJo-Medium, Haettenschweiler, Harlow Solid Italic Italic, Harrington, Headline R, High Tower Text, High Tower Text Italic, HoloLens MDL2 Assets, Impact, Imprint MT Shadow, Informal Roman, Ink Free, Javanese Text, Jokerman, Juice ITC, Kristen ITC, Kunstler Script, Leelawadee UI, Leelawadee UI Bold, Lucida Bright, Lucida Bright Bold, Lucida Bright Italic, Lucida Bright Bold Italic, Lucida Calligraphy, Lucida Console, Lucida Fax, Lucida Fax Bold, Lucida Fax Italic, Lucida Fax Bold Italic, Lucida Handwriting, Lucida Sans, Lucida Sans Bold, Lucida Sans Italic, Lucida Sans Bold Italic, Lucida Sans Typewriter, Lucida Sans Typewriter Bold, Lucida Sans Typewriter Italic, Lucida Sans Typewriter Bold Italic, Lucida Sans Unicode, MS Gothic, MS Outlook, MS PGothic, MS Reference Sans Serif, MS Reference Specialty, MS UI Gothic, MV Boli, Magic R, Magneto Bold, Maiandra GD, Malgun Gothic, Malgun Gothic Bold, Marlett, Matura MT Script Capitals, Meiryo, Meiryo Bold, Meiryo Italic, Meiryo Bold Italic, Meiryo UI, Meiryo UI Bold, Meiryo UI Italic, Meiryo UI Bold Italic, Microsoft Himalaya, Microsoft JhengHei, Microsoft JhengHei Bold, Microsoft JhengHei UI, Microsoft JhengHei UI Bold, Microsoft New Tai Lue, Microsoft New Tai Lue Bold, Microsoft PhagsPa, Microsoft PhagsPa Bold, Microsoft Sans Serif, Microsoft Tai Le, Microsoft Tai Le Bold, Microsoft YaHei, Microsoft YaHei Bold, Microsoft YaHei UI, Microsoft YaHei UI Bold, Microsoft Yi Baiti, MingLiU-ExtB, MingLiU_HKSCS-ExtB, Mistral, Modern No. 20, MoeumT R, Mongolian Baiti, Monotype Corsiva Italic, Myanmar Text, Myanmar Text Bold, NSimSun, New Gulim, Niagara Engraved, Niagara Solid, Nirmala UI, Nirmala UI Bold, OCR A Extended, Old English Text MT, Onyx, PMingLiU-ExtB, Palace Script MT Italic, Palatino Linotype, Palatino Linotype Bold, Palatino Linotype Italic, Palatino Linotype Bold Italic, Papyrus, Parchment, Perpetua, Perpetua Bold, Perpetua Italic, Perpetua Bold Italic, Perpetua Titling MT, Perpetua Titling MT Bold, Playbill, Poor Richard, Pristina, Pyunji R, Rage Italic, Ravie, Rockwell, Rockwell Bold, Rockwell Italic, Rockwell Bold Italic, Rockwell Condensed, Rockwell Condensed Bold, Rockwell Extra Bold, Script MT Bold, Segoe MDL2 Assets, Segoe Print, Segoe Print Bold, Segoe Script, Segoe Script Bold, Segoe UI, Segoe UI Bold, Segoe UI Italic, Segoe UI Bold Italic, Segoe UI Emoji, Segoe UI Historic, Segoe UI Symbol, Showcard Gothic, SimSun, SimSun-ExtB, Sitka Banner, Sitka Banner Bold, Sitka Banner Italic, Sitka Banner Bold Italic, Sitka Display, Sitka Display Bold, Sitka Display Italic, Sitka Display Bold Italic, Sitka Heading, Sitka Heading Bold, Sitka Heading Italic, Sitka Heading Bold Italic, Sitka Small, Sitka Small Bold, Sitka Small Italic, Sitka Small Bold Italic, Sitka Subheading, Sitka Subheading Bold, Sitka Subheading Italic, Sitka Subheading Bold Italic, Sitka Text, Sitka Text Bold, Sitka Text Italic, Sitka Text Bold Italic, Snap ITC, Stencil, Sylfaen, Symbol, Tahoma, Tahoma Bold, Tempus Sans ITC, Times New Roman, Times New Roman Bold, Times New Roman Italic, Times New Roman Bold Italic, Trebuchet MS, Trebuchet MS Bold, Trebuchet MS Italic, Trebuchet MS Bold Italic, Tw Cen MT, Tw Cen MT Bold, Tw Cen MT Italic, Tw Cen MT Bold Italic, Tw Cen MT Condensed, Tw Cen MT Condensed Bold, Tw Cen MT Condensed Extra Bold, Verdana, Verdana Bold, Verdana Italic, Verdana Bold Italic, Viner Hand ITC, Vivaldi Italic, Vladimir Script, Webdings, Wide Latin, Wingdings, Wingdings 2, Wingdings 3, Yet R, Yu Gothic, Yu Gothic Bold, Yu Gothic UI, Yu Gothic UI Bold
[Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
[Info   :XUnity.AutoTranslator] Loaded TextMesh Pro font uses version: 1.1.0
[Warning:XUnity.AutoTranslator] TextMesh Pro version mismatch. Font asset version: 1.1.0, TextMesh Pro version: 1.4.0
[Info   :XUnity.AutoTranslator] Loaded fallback font for TextMesh Pro: arialuni_sdf_u2019
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2022.3.48f1] game.
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
```

### Environment

```markdown
- OS:window10
- BepInEx: BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.725+e1974e2
- Game: ASKA
```

**Comment by wappenull** [comment]
### Added: temporary workaround for me.

- Create "steam_appid.txt" text file in game exe folder. Fill the file content with game's app id (in my case it is 1694420) you can check your game appid from store page URL.
- Launch the game EXE directly instead of from Steam. Bepin console will come up normally and works.
- Explain: Steam dll code that embedded in the game will have a development check switch if the specific text file "steam_appid.txt" is in place, it will enter development mode and not attempt to relaunch a game via Steam client. Thus this is how this workaround works.

![image](https://github.com/user-attachments/assets/08876369-28cc-40a5-bb23-0a571d2f5234)

Note that launching the app this way you will probably lose some Steam functionality including Steam Invite or Overlay, or probably achievement trigger (?). Not sure.
