### ISSUE TITLE
BepIN EX Bleeding Edge Build Completely Crashes Rune Factory 5; Error With dobby.dll

### ISSUE THREAD

**Issue by BigOtaku2118** [BepInEx/BepInEx#504]
### What happened?

So, I USED to have NO problem getting the BepIN EX mod loader to work with RF5. Long story short. I went into the hospital, my Mother got into my computer without my permission, upgraded it to Windows 11, and f$%^ed it to Hell and back.
Had to do a complete Clean Install of Windows 10 to get it to where it was before. The old BepIN EX build I used to install mods no longer works, forcing me to use the IL2CPP Bleeding Edge build.
I do what I did before. Copy-pasted everything from the extracted file into the RF5 base folder before going to run the game.
NUMEROUS attempts to see what I'm doing wrong ALWAYS ends up with the same error message during Pre-Loading... What is going on?
[preloader_20221030_124709_945.log](https://github.com/BepInEx/BepInEx/files/9896477/preloader_20221030_124709_945.log)

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
System.DllNotFoundException: Unable to load DLL 'dobby' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BepInEx.Unity.IL2CPP.Hook.Dobby.DobbyLib.Prepare(IntPtr target, IntPtr replacement, IntPtr* originalCall)
   at BepInEx.Unity.IL2CPP.Hook.Dobby.DobbyDetour.PrepareImpl() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Hook/Dobby/DobbyDetour.cs:line 14
   at BepInEx.Unity.IL2CPP.Hook.BaseNativeDetour`1.Prepare() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Hook/BaseNativeDetour.cs:line 88
   at BepInEx.Unity.IL2CPP.Hook.BaseNativeDetour`1.GenerateTrampoline(MethodBase signature) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Hook/BaseNativeDetour.cs:line 65
   at BepInEx.Unity.IL2CPP.Hook.BaseNativeDetour`1.GenerateTrampoline[TDelegate]() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Hook/BaseNativeDetour.cs:line 77
   at BepInEx.Unity.IL2CPP.Hook.INativeDetour.CacheDetourWrapper.GenerateTrampoline[T]() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Hook/INativeDetour.cs:line 83
   at BepInEx.Unity.IL2CPP.Hook.INativeDetour.CreateAndApply[T](IntPtr from, T to, T& original) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Hook/INativeDetour.cs:line 48
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.Initialize(String gameExePath) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 72
   at BepInEx.Unity.IL2CPP.Preloader.Run() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Preloader.cs:line 87
   at BepInEx.Unity.IL2CPP.UnityPreloaderRunner.PreloaderMain() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/UnityPreloadRunner.cs:line 29
   at Doorstop.Entrypoint.Start() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/DoorstopEntrypoint.cs:line 39
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: Unity IL2CPP Bleeding Edge Build X64 (Artifact 662)
- Game: Rune Factory 5
```

**Comment by blackjack4494** [comment]
Dobby requires vc++ redist
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
Download this one https://aka.ms/vs/17/release/vc_redist.x64.exe
