### ISSUE TITLE
Failed to download unity base libraries

### ISSUE THREAD

**Issue by SUPER69T** [BepInEx/BepInEx#515]
### What happened?

crash on laun
![image](https://user-images.githubusercontent.com/118633104/202869112-9c1c90a8-dad5-4b93-b606-f35486d61b88.png)
ch

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.662 - GTFO
[Message: Preloader] Built from commit 3ad398a160d0d138a2d012978e6709e20589cf82
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2019.4.21f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.DownloadUnityAssemblies() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 237
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.GenerateInteropAssemblies() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 201
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
```

### Environment

```markdown
- OS: win10
- BepInEx: 3.1.0
- Game: GTFO
```

**Comment by stas1186** [comment]
same problem

**Comment by stas1186** [comment]
![probl](https://user-images.githubusercontent.com/127501004/224307302-04e12155-5c93-4bfa-b93f-cbe4e6d465ee.jpg)

**Comment by SUPER69T** [comment]
I got kinda frustrated of this whole downloading mods thing I gave up and
uninstalled it all

**Comment by stas1186** [comment]
I only have this problem on one computer. On another computer and on a laptop, there is no such problem. I don't understand what is the reason.

**Comment by SUPER69T** [comment]
Is the operating system dufferent on the non working computer?

**Comment by stas1186** [comment]
No. Everywhere Win 10 64

**Comment by SUPER69T** [comment]
Rip bozo🗿

**Comment by stas1186** [comment]
Hi dude! I solved the problem! I just needed another internet connection. I connected the phone as a modem and there were no problems. So the original Internet had some kind of port problem or something like that.

**Comment by SUPER69T** [comment]
Lmao. Hella weird. Thank you, I'll try that.

**Comment by vorton1** [comment]
I just wanted to add in case anyone else has this problem in the future and comes across this page. If you are using a vpn disable it. I was bashing my head against the wall trying to figure out what was going on until I came across this post and tried disabling my vpn. Hopefully this will help someone else.

**Comment by camer5** [comment]
Im also having this issue but i am not using any form of vpn so there is just no fix for me im asking the people in the bepinex discord but they havent given me anything to fix it yet

**Comment by fhonts** [comment]
Same problem.I am from China. I only speak some English.I am using a vpn too.But i don't know why the BepinEx can't download any files!

**Comment by wockkkk** [comment]
I have the same problem in China

**Comment by Holozok** [comment]
yes! just use cellular data via hotspot from smartphone and it works.

**Comment by Aleonz00** [comment]
I have the game's access to internet blocked (because I don't trust BepInEx) and downloaded the libraries separately from https://unity.bepinex.dev/libraries/ and installed it in BepInEx\interop but it's STILL trying to connect to the internet to 'download' the libraries and because it can't, it forces the game closed! That's really shady... It doesn't even try to look to see if the libraries are already installed? Really???

**Comment by Suioji** [comment]
try changing the DNS, I use Warp 1.1.1.1 and it works

**Comment by ManlyMarco** [comment]
I've had reports that having Bitdefender installed causes this issue, even if it's turned off.

**Comment by ManlyMarco** [comment]
Since #1213 was merged, this issue can be worked around now:
1. Update BepInEx to at least `bleeding edge #752`
2. Manually download the required library zip from https://unity.bepinex.dev/libraries
3. Place the downloaded zip file in the `BepInEx\unity-libs` folder, the name must not be changed
4. BepInEx should now use the downloaded zip file instead of trying to download it

For more info check the description of `UnityBaseLibrariesSource` in `BepInEx\config\BepInEx.cfg`.
