### ISSUE TITLE
BepIn won't Launch/Installed

### ISSUE THREAD

**Issue by BrainSoup69** [BepInEx/BepInEx#535]
### What happened?

well I tried for many hours already on trying to installing it but it seem to never worked. 
Trying to find the file and all also difficult and never showed up either. 
This is what it said when I try to installing it. 

Unhandled exception
System.IO.FileNotFoundException: Could not load file or assembly 'BepInEx.Preloader.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'BepInEx.Preloader.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BepInEx.NET.Framework.Launcher.NetPreloaderRunner.OuterMain(String[] args, String filename)
   at BepInEx.NET.Framework.Launcher.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Press enter to exit...

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Unhandled exception
System.IO.FileNotFoundException: Could not load file or assembly 'BepInEx.Preloader.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'BepInEx.Preloader.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BepInEx.NET.Framework.Launcher.NetPreloaderRunner.OuterMain(String[] args, String filename)
   at BepInEx.NET.Framework.Launcher.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Press enter to exit...
```

### Environment

```markdown
- OS: 
- BepInEx: 
- Game:
```

**Comment by ChickenChunk579** [comment]
I have the same error
### Log Outputs
```
System.IO.FileNotFoundException: Could not load file or assembly 'BepInEx.Preloader.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'BepInEx.Preloader.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BepInEx.NET.Framework.Launcher.NetPreloaderRunner.OuterMain(String[] args, String filename)
   at BepInEx.NET.Framework.Launcher.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
### Environment
- OS: Windows 10
- BepInEx: 6.0.0 netframework452
- Game: Celeste (FNA)

**Comment by cybervand** [comment]
I just found a fix! So after having all the files unzipped and zipped and deleted and unzipped again, i had to decompile BepInEX to find out what it was exactly. 

its a Block by windows `Zone.Identifier`  more specifically `Operation is not supported. (Exception from HRESULT: 0x80131515)` and its caused by the firewall on windows.

 Windows identifies that its a file downloaded by the internet and blocks it from opening which causes not only the problem where BepIn cant look outside of the root folder its in, mods also get banned as well so even if you extract everything to the root folder, the mods also wont work. the fix is a one liner in powershell:

`Get-ChildItem -Path "PATH-TO-FILE(c:\etc)" -Recurse -File | Unblock-File`

 but i created a lill script you can run that you can save as a ps1 for later.

 ```
$ErrorActionPreference = "Stop"

function Get-TargetDirectory {
    if (-not [string]::IsNullOrWhiteSpace($PSScriptRoot)) {
        return $PSScriptRoot
    }

    if ($MyInvocation.MyCommand.Path) {
        return Split-Path -Parent $MyInvocation.MyCommand.Path
    }

    return (Get-Location).Path
}

function Pause-For-User {
    try {
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    }
    catch {
        Read-Host | Out-Null
    }
}

$targetDirectory = Get-TargetDirectory

Write-Host "This script will scan the directory it is in and all subfolders for blocked files."
Write-Host
Write-Host ("Directory: {0}" -f $targetDirectory)
Write-Host
Write-Host "If any files have the Windows download block (Zone.Identifier), it will remove that block."
Write-Host

$confirmation = Read-Host "Do you want to unblock this directory? (Y/N)"
if ($confirmation -notmatch '^(y|yes)$') {
    Write-Host
    Write-Host "No changes were made."
    Write-Host "Press any key to continue."
    Pause-For-User
    exit 0
}

$files = Get-ChildItem -LiteralPath $targetDirectory -Recurse -File -Force

if (-not $files) {
    Write-Host
    Write-Host ("No files found in '{0}'." -f $targetDirectory)
    Write-Host "Done unblocking file/folder! Press any key to continue."
    Pause-For-User
    exit 0
}

$blockedFiles = @()
foreach ($file in $files) {
    if (Get-Item -LiteralPath $file.FullName -Stream Zone.Identifier -ErrorAction SilentlyContinue) {
        $blockedFiles += $file
    }
}

Write-Host
if ($blockedFiles) {
    $blockedFiles | Unblock-File
    Write-Host ("Unblocked {0} file(s) in '{1}'." -f $blockedFiles.Count, $targetDirectory)
}
else {
    Write-Host ("No blocked files found in '{0}'." -f $targetDirectory)
}

Write-Host "Done unblocking file/folder! Press any key to continue."
Pause-For-User
```
