### ISSUE TITLE
Game crash when patched method with nullable parameters is called

### ISSUE THREAD

**Issue by UntiIted** [BepInEx/BepInEx#566]
### What happened?

Several methods seems to crash the game and from what I observed the common thing seems to be that a patched method is called that contains Nullable parameters, example screenshot below.

![image](https://user-images.githubusercontent.com/47327388/223802841-008f79dc-d803-415a-98f3-ed52a96b9785.png)

Additionally, trying to call the method from code without it being patched will throw a NullReferenceException, but it's hard to say if that's a bug on BepInEx side because we don't have the source code for the game.

The 1st error in the logs provided is the one that crashes the game, the 2nd error is from calling the method from code.

### Steps to reproduce

This example is for a specific method in GTFO, but if the theory is right, any nullable parameter method should work
Simply patch Dam_PlayerDamageBase.OnIncomingDamage, open GTFO, take damage from any source and the game will crash.

        [HarmonyPatch(typeof(Dam_PlayerDamageBase), nameof(Dam_PlayerDamageBase.OnIncomingDamage))]
        [HarmonyPrefix]
        public static void OnIncomingDamage()
        {

        }

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_value_box(IntPtr, IntPtr)
--------------------------------
   at DynamicClass.(il2cpp -> managed) OnIncomingDamage(il2cpp -> managed) OnIncomingDamage(IntPtr, Single, Single, IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)



System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtrNotNull(Il2CppObjectBase obj) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/IL2CPP.cs:line 222
   at Dam_PlayerDamageBase.OnIncomingDamage(Single damage, Single originalDamage, Nullable`1 source)
```

### Environment

```markdown
- OS: Windows
- BepInEx: Bleeding Edge IL2CPP windowsx64 #668 (Build Date 3/6/2023)
- Game: GTFO
```

**Comment by garryspins** [comment]
bump

**Comment by d3xMachina** [comment]
I have the exact same issue on Final Fantasy VI (and other FF Pixel Remaster games) on BepInEx BE 691 and 577 :

The method in question :
```
// RVA: 0x34CE80 Offset: 0x34BE80 VA: 0x18034CE80
public static float GetFieldSpriteMoveSecondsPerCell(Nullable<FieldEntityConstants.FieldSpriteSpeedID> speedId, float entityMoveMagnification = 1) { }
```

My hook :
```
[HarmonyPatch(typeof(FieldEntityConstants), nameof(FieldEntityConstants.GetFieldSpriteMoveSecondsPerCell))]
[HarmonyPostfix]
static void SpriteMovespeed(ref float __result, Il2CppSystem.Nullable<FieldEntityConstants.FieldSpriteSpeedID> speedId, float entityMoveMagnification)
{
}
```

Error.log :
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
  at Il2CppInterop.Runtime.IL2CPP.il2cpp_value_box(IntPtr, IntPtr)
--------------------------------
  at DynamicClass.(il2cpp -> managed) GetFieldSpriteMoveSecondsPerCell(il2cpp -> managed) GetFieldSpriteMoveSecondsPerCell(IntPtr, Single, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
```

To reproduce : 
Move your character, that will call the method and crash.

**Comment by foxwhite25** [comment]
Still exist to this day, can confirm
