### ISSUE TITLE
"Monochrome Mobius: Rights and Wrongs Forgotten" crashes on startup.

### ISSUE THREAD

**Issue by KingKrouch** [BepInEx/BepInEx#579]
### What happened?

Attempting to use the 32-Bit IL2CPP build of BepInEx 6 Nightly doesn't result in successfully hooking to the game.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.668 - MonochromeMobius Rights and Wrongs Forgotten
[Message: Preloader] Built from commit 46e297f210c27e9b4d26e7cd326625b53c83faa0
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2020.3.29f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   :InteropManager] Detected outdated interop assemblies, will regenerate them now
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Info   :    Cpp2IL] [Library] Using actual IL2CPP Metadata version 27.1
[Info   :    Cpp2IL] [Library] Initialized Metadata in 165ms
[Info   :    Cpp2IL] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info   :    Cpp2IL] [Library] Searching Binary for Required Data...
[Info   :    Cpp2IL] [Library] Got Binary codereg: 0x12A91478, metareg: 0x12A95598 in 107ms.
[Info   :    Cpp2IL] [Library] Initializing Binary...
[Info   :    Cpp2IL] [Library] Initialized Binary in 134ms
[Info   :    Cpp2IL] [Library] Mapping pointers to Il2CppMethodDefinitions...
[Info   :    Cpp2IL] [Library] Processed 92005 OK (43ms)
[Info   :    Cpp2IL] [Program] Creating application model...
[Info   :    Cpp2IL] [Program] Application model created in 1032.0041ms
[Info   :InteropManager] Cpp2IL finished in 00:00:04.7043204
[Info   :InteropManager] Generating interop assemblies
[Info   :Il2CppInteropGen] Reading assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0362915
[Info   :Il2CppInteropGen] Reading unity assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:01.5053402
[Info   :Il2CppInteropGen] Creating rewrite assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0065141
[Info   :Il2CppInteropGen] Computing renames...
[Info   :Il2CppInteropGen] Done in 00:00:00.0320559
[Info   :Il2CppInteropGen] Creating typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0303755
[Info   :Il2CppInteropGen] Computing struct blittability...
[Info   :Il2CppInteropGen] Done in 00:00:00.0405851
[Info   :Il2CppInteropGen] Filling typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0268288
[Info   :Il2CppInteropGen] Filling generic constraints...
[Info   :Il2CppInteropGen] Done in 00:00:00.0045021
[Info   :Il2CppInteropGen] Creating members...
[Info   :Il2CppInteropGen] Done in 00:00:00.7758595
[Info   :Il2CppInteropGen] Scanning method cross-references...
[Info   :Il2CppInteropGen] Done in 00:00:00.0252435
[Info   :Il2CppInteropGen] Finalizing method declarations...
[Info   :Il2CppInteropGen] Done in 00:00:00.8334892
[Info   :Il2CppInteropGen] 0 total potentially dead methods
[Info   :Il2CppInteropGen] Filling method parameters...
[Info   :Il2CppInteropGen] Done in 00:00:00.2174604
[Info   :Il2CppInteropGen] Creating static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.3500302
[Info   :Il2CppInteropGen] Creating value type fields...
[Info   :Il2CppInteropGen] Done in 00:00:00.0220504
[Info   :Il2CppInteropGen] Creating enums...
[Info   :Il2CppInteropGen] Done in 00:00:00.0242894
[Info   :Il2CppInteropGen] Creating IntPtr constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.1311495
[Info   :Il2CppInteropGen] Creating non-blittable struct constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0117641
[Info   :Il2CppInteropGen] Creating generic method static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0623560
[Info   :Il2CppInteropGen] Creating field accessors...
[Info   :Il2CppInteropGen] Done in 00:00:01.2176906
[Info   :Il2CppInteropGen] Filling methods...
[Info   :Il2CppInteropGen] Done in 00:00:01.3547441
[Info   :Il2CppInteropGen] Generating implicit conversions...
[Info   :Il2CppInteropGen] Done in 00:00:00.0132851
[Info   :Il2CppInteropGen] Creating properties...
[Info   :Il2CppInteropGen] Done in 00:00:00.0618735
[Info   :Il2CppInteropGen] Unstripping types...
[Info   :Il2CppInteropGen] Done in 00:00:00.0911778
[Info   :Il2CppInteropGen] Unstripping fields...
[Info   :Il2CppInteropGen] Restored 669 fields
[Info   :Il2CppInteropGen] Failed to restore 22 fields
[Info   :Il2CppInteropGen] Done in 00:00:00.0071985
[Info   :Il2CppInteropGen] Unstripping methods...
[Info   :Il2CppInteropGen] Restored 15422 methods
[Info   :Il2CppInteropGen] Failed to restore 1024 methods
[Info   :Il2CppInteropGen] Done in 00:00:00.2349709
[Info   :Il2CppInteropGen] Unstripping method bodies...
[Info   :Il2CppInteropGen] IL unstrip statistics: 6992 successful, 3175 failed
[Info   :Il2CppInteropGen] Done in 00:00:00.4985989
[Info   :Il2CppInteropGen] Writing xref cache...
[Info   :Il2CppInteropGen] Done in 00:00:00.0251430
[Info   :Il2CppInteropGen] Writing assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:02.8324820
[Info   :Il2CppInteropGen] Writing method pointer map...
[Info   :Il2CppInteropGen] Done in 00:00:00.6735339
[Info   :Il2CppInteropGen] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.FindGetTypeInfoFromTypeDefinitionIndex(Boolean forceICallMethod) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 269
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 68
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 188
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 242
   at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 88
```

### Environment

```markdown
- OS: Windows 11 Pro Workstation (x64)
- BepInEx: BepInEx 6.0.0-be.668
- Game: Monochrome Mobius: Rights and Wrongs Forgotten
```

**Comment by Albeoris** [comment]
Same problem. Persona 5 Tactica:

```
[Message: Preloader] BepInEx 6.0.0-be.674 - Persona 5 Tactica
[Message: Preloader] Built from commit 82077ec7c91c97f0e5f8ada5d178fd7ece6c0099
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Il2CppInterop.Runtime.Injection.Hooks.GenericMethod_GetMethod_Hook.FindTargetMethod() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/Hooks/GenericMethod_GetMethod_Hook.cs:line 67
   at Il2CppInterop.Runtime.Injection.Hook`1.ApplyHook() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/Hook.cs:line 30
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 75
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 195
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 244
   at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 88
```

**Comment by Albeoris** [comment]
Okay, I was able to solve this problem by disabling log handling in the BepInEx config:

```
[Logging]

## Enables showing unity log messages in the BepInEx logging system.
# Setting type: Boolean
# Default value: true
UnityLogListening = false
```

**Comment by Albeoris** [comment]
Workaround: I saw that there is UniRx library. So I instantiated MainThreadDispatcher and subscribed to the events instead of registering my own component.

**Comment by KingKrouch** [comment]
Yeah, even with that fix and the latest bleeding edge builds of BIE, this game still crashes.

**Comment by KingKrouch** [comment]
This is without plugins.

**Comment by karaok1** [comment]
> This is without plugins.

Any solution yet? I have the same problem with another game. 
@Albeoris
