### ISSUE TITLE
Preloader stopped working after updating "Sons of the forrest"

### ISSUE THREAD

**Issue by Zabbel** [BepInEx/BepInEx#601]
### What happened?

Just tried to start the game after updating....

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
Preloader Error Log:
System.IO.IOException: Invalid handle.
   at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at BepInEx.Logging.ConsoleLogListener.LogEvent(Object sender, LogEventArgs eventArgs) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Logging/ConsoleLogListener.cs:line 23
   at BepInEx.Logging.Logger.InternalLogEvent(Object sender, LogEventArgs eventArgs) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Logging/Logger.cs:line 45
   at BepInEx.Logging.ManualLogSource.Log(LogLevel level, Object data) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Logging/ManualLogSource.cs:line 35
   at BepInEx.Unity.IL2CPP.Preloader.Run() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Preloader.cs:line 91
   at BepInEx.Unity.IL2CPP.UnityPreloaderRunner.PreloaderMain() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/UnityPreloadRunner.cs:line 29
   at Doorstop.Entrypoint.Start() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/DoorstopEntrypoint.cs:line 39
```

### Environment

```markdown
- OS:Ubuntu 23.04 
- BepInEx: 6.0.0-be.668
- Game: Sons of the forrest
```

**Comment by Enovale** [comment]
I'm getting this too after reinstalling a different game and bepinex, happens with no mods or configuration changes so im clueless
