### ISSUE TITLE
il2cpp game crashed after launch

### ISSUE THREAD

**Issue by gggssepgf** [BepInEx/BepInEx#689]
### What happened?

I tried BE 6.00-674 and BE 6.00-673，they both crashed，but had different error outputs
the game is using unity 2023.1.15f1.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
6.0.0-673 logs:

[Message: Preloader] BepInEx 6.0.0-be.673 - DeadEndCity
[Message: Preloader] Built from commit 06a7278f80072182492213601d54185febe26efd
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2023.1.15f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain

error logs：

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)
--------------------------------
   at Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase.get_Pointer()
   at Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtrNotNull(Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase)
   at Il2CppSystem.Type.GetMethod(System.String)
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Delegate)
   at UnityEngine.Application+LogCallback.op_Implicit(System.Action`3<System.String,System.String,UnityEngine.LogType>)
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr, IntPtr, IntPtr, IntPtr)

6.0.0-674 logs：

[Message: Preloader] BepInEx 6.0.0-be.674 - DeadEndCity
[Message: Preloader] Built from commit 82077ec7c91c97f0e5f8ada5d178fd7ece6c0099
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2023.1.15f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Warning:     Unity] load playlog.dat sync. NotFound

error logs:

Fatal error. Internal CLR error. (0x80131506)
```

### Environment

```markdown
- OS: win11
- BepInEx: 6.0.0-674 || 6.0.0-673
- Game: deadend city
```

**Comment by karaok1** [comment]
I am having the same issue. Have you find a solution?
