### ISSUE TITLE
Fatal error. System.AccessViolationException

### ISSUE THREAD

**Issue by Pandamonia0** [BepInEx/BepInEx#720]
### What happened?

Start the game up, gets this far then closes.
![image](https://github.com/BepInEx/BepInEx/assets/152452977/bea0aa0f-749e-48e1-bb8f-93f7113d22f8)

### Steps to reproduce

Just default installation, nothing changed.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Interop+WinHttp.WinHttpOpen(IntPtr, UInt32, System.String, System.String, Int32)
--------------------------------
   at System.Net.Http.HttpWindowsProxy.TryCreate(System.Net.IWebProxy ByRef)
   at System.Net.Http.SystemProxyInfo.ConstructSystemProxy()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at System.Net.Http.HttpClient+<>c.<get_DefaultProxy>b__15_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Func`1<System.__Canon>)
   at System.Net.Http.HttpClient.get_DefaultProxy()
   at System.Net.Http.HttpConnectionPoolManager..ctor(System.Net.Http.HttpConnectionSettings)
   at System.Net.Http.SocketsHttpHandler.SetupHandlerChain()
   at System.Net.Http.SocketsHttpHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient+<GetStreamAsyncCore>d__51.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpClient+<GetStreamAsyncCore>d__51, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<GetStreamAsyncCore>d__51 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpClient+<GetStreamAsyncCore>d__51, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<GetStreamAsyncCore>d__51 ByRef)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsync(System.Uri, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsync(System.String)
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.DownloadUnityAssemblies()
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.GenerateInteropAssemblies()
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.Initialize()
   at BepInEx.Unity.IL2CPP.Preloader.Run()
   at BepInEx.Unity.IL2CPP.UnityPreloaderRunner.PreloaderMain()
   at Doorstop.Entrypoint.Start()
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.674+82077ec (though have tried with old version too that I don't remember exact build numbers)
- Game: Price for freedom 30.1
```

**Comment by Redbullsenpai** [comment]
Same here , tried to run it with dave the diver (pir) and it did this exact thing. have u found a fix?

**Comment by sabdol** [comment]
For anyone who struggle on this, I had same issue and found solution for this. I am on Windows 11.

What I did is, simply disable all proxy settings, both auto and manual one, on network settings and it works.

**Comment by new85-cyber** [comment]
> For anyone who struggle on this, I had same issue and found solution for this. I am on Windows 11.
> 
> What I did is, simply disable all proxy settings, both auto and manual one, on network settings and it works.

OMG, I spent days hopelessly googled for the solution and this fixed my issue. Thank you so much. You are genius!!!!
