### ISSUE TITLE
BepInEx 6 crashes when Unity log is enabled

### ISSUE THREAD

**Issue by karaok1** [BepInEx/BepInEx#744]
### What happened?

`UnityLogListening = true` game crashes.
`UnityLogListening = false` works but now I can't see Unity logs.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.682 - Seafight
[Message: Preloader] Built from commit 910844a982dbb126d0c6544847424bc42fb7849c
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2022.3.8f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.NullReferenceException: Couldn't find System.Type for Il2Cpp type: System.
   at Il2CppInterop.Runtime.Injection.ClassInjector.SystemTypeFromIl2CppType(Il2CppTypeStruct* typePointer) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 1144
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 432
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 244
   at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 88
```

### Environment

```markdown
- OS: Windows 64
- BepInEx: BepInEx 6 latest nightly build (682)
- Game: Seafight
```

**Comment by kekanzek** [comment]
Were you ever able to see Unity logs before BepInEx was added? In any way possible did you admit flags such as -nologs to the game? Is this launched through Steam? 

I honestly don't know why this is happening. This is _**Bleeding Edge**_ BepInEx, so it's not unexpected. Either way, are you able to use an earlier version of BepInEx for your game?

**Comment by akchama** [comment]
> Were you ever able to see Unity logs before BepInEx was added? In any way possible did you admit flags such as -nologs to the game? Is this launched through Steam?
> 
> I honestly don't know why this is happening. This is _**Bleeding Edge**_ BepInEx, so it's not unexpected. Either way, are you able to use an earlier version of BepInEx for your game?

I see, the game got updated and now it works but I don't know if it is related with the update or I had some bad files or other settings that caused this problem. I will try to replicate it and see if I can reproduce this again.

**Comment by akchama** [comment]
Issue still persists.

**Comment by ImanCol** [comment]
same problem

**Comment by Caritusy** [comment]
That's a issue of [Il2CppInterop](https://github.com/BepInEx/Il2CppInterop), that meaning if you are using any stuff with [Il2CppInterop](https://github.com/BepInEx/Il2CppInterop) your game will brokes and crashes for any unknown reasons.
Only way to solve this is stop using any stuff from [Il2CppInterop](https://github.com/BepInEx/Il2CppInterop), hooking unity logging used `DelegateSupport` class and it from [Il2CppInterop](https://github.com/BepInEx/Il2CppInterop).

**Comment by ImanCol** [comment]
So....how fix?

**Comment by ImanCol** [comment]
> Set `UnityLogging` as `false`

That's not a solution, it's an escape. It's like disabling something you still want to use.

**Comment by Caritusy** [comment]
> > Set `UnityLogging` as `false`
> 
> That's not a solution, it's an escape. It's like disabling something you still want to use.

Using UnityLogListening = using DelegateSupport = game brokes and no way to fix.
The be versions still using il2cppInterop 1.4.6, and i don't know is really this fixed in 1.5.0 or not.
So stop using UnityLogListening is not a escape unless there's really a solution to fix this.
