### ISSUE TITLE
Error at il2cpp_runtime_invoke 

### ISSUE THREAD

**Issue by akchama** [BepInEx/BepInEx#746]
### What happened?

I created a very basic plugin, when I use `AddComponent<T>();` I get an error during call to `il2cpp_runtime_invoke`

```cs
public class TestPluginBehaviour : MonoBehaviour
{
    private void Update()
    {

    }
}

[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
public class Plugin : BasePlugin
{
    public override void Load()
    {
        // Plugin startup logic
        Log.LogInfo($"Plugin {MyPluginInfo.PLUGIN_GUID} is loaded!");

        ClassInjector.RegisterTypeInIl2Cpp<TestPluginBehaviour>();

        var go = new GameObject();
        go = new("TestPluginBehaviourGO");
        go.AddComponent<TestPluginBehaviour>();
        GameObject.DontDestroyOnLoad(go);
    }
}
```

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Fatal error. 0xC0000005
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr, IntPtr, IntPtr, IntPtr)
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
   at UnityEngine.GameObject.AddComponent[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at SeafightKraknBot.Plugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(BepInEx.PluginInfo, System.Reflection.Assembly)
   at BepInEx.Bootstrap.BaseChainloader`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoadPlugins(System.Collections.Generic.IList`1<BepInEx.PluginInfo>)
   at BepInEx.Bootstrap.BaseChainloader`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr, IntPtr, IntPtr, IntPtr)
```
```


### Environment

```markdown
- OS: Windows 11 Pro
- BepInEx: 6
- Game: Seafight
```

**Comment by akchama** [comment]
> You're probably running this code too early; you're trying to create a game object at the same time that the scene is changing by doing it in Load() before Internal_ActiveSceneChanged() has finished execution. Maybe move it to a later callback like Awake or Start?

I think this issue is related to something else. Below there is a history of events and what leads to this error:

When I install BepInEx and run for the first time I get this error:
```
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.NullReferenceException: Couldn't find System.Type for Il2Cpp type: System.
   at Il2CppInterop.Runtime.Injection.ClassInjector.SystemTypeFromIl2CppType(Il2CppTypeStruct* typePointer) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 1144
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 432
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 244
   at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 88
```


If I disable logs like this  `UnityLogListening = false`
Game works again...

But if I put a very simple plugin like this:

```
public class TestPluginBehaviour : MonoBehaviour
{
    private void Update()
    {

    }
}

[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
public class Plugin : BasePlugin
{
    public override void Load()
    {
        SceneManager.sceneLoaded += (Action<Scene,LoadSceneMode>)((scene, loadMode) =>
        {
            ClassInjector.RegisterTypeInIl2Cpp<TestPluginBehaviour>();

            var go = new GameObject();
            go = new("TestPluginBehaviourGO");
            go.AddComponent<TestPluginBehaviour>();
            GameObject.DontDestroyOnLoad(go);
        });
    }
}
```


I get the error in my first post.

Even if you could help me to understand how I can debug this, it would be very helpful!

**Comment by MillzyDev** [comment]
As I said, `Load()` is too early to be making UnityEngine calls, try using `Awake()` or `Start()`

**Comment by akchama** [comment]
> As I said, `Load()` is too early to be making UnityEngine calls, try using `Awake()` or `Start()`

How would that work? This is il2cpp and without mono behaviour `Awake` won't be registered. I need to Inject a MonoBehaviour object in the first place to call Awake from there

**Comment by MillzyDev** [comment]
> > As I said, `Load()` is too early to be making UnityEngine calls, try using `Awake()` or `Start()`
> 
> How would that work? This is il2cpp in .NET 6 and without mono behaviour `Awake` won't be registered. I need to Inject a MonoBehaviour object in the first place to call Awake from there

Oh my god, you're completely right, I'm so sorry; I've been using other loaders and i forgot. 

Anyway, moving past that: I believe injected IL2CPP types need a constructor that takes an `IntPtr` parameter.
Something like
 ```cs
public class TestPluginBehaviour : MonoBehaviour
{
    public TestPluginBehaviour(IntPtr ptr) : base(ptr)
    {
    }
    
    private void Update()
    {
    
    }
}
```

**Comment by akchama** [comment]
> > > As I said, `Load()` is too early to be making UnityEngine calls, try using `Awake()` or `Start()`
> > 
> > 
> > How would that work? This is il2cpp in .NET 6 and without mono behaviour `Awake` won't be registered. I need to Inject a MonoBehaviour object in the first place to call Awake from there
> 
> Oh my god, you're completely right, I'm so sorry; I've been using other loaders and i forgot.
> 
> Anyway, moving past that: I believe injected IL2CPP types need a constructor that takes an `IntPtr` parameter. Something like
> 
> ```cs
> public class TestPluginBehaviour : MonoBehaviour
> {
>    public TestPluginBehaviour(IntPtr ptr) : base(ptr)
>    {
>    }
>    
>    private void Update()
>    {
>    
>    }
> }
> ```
> 
> Maybe try that?

This is not a plugin related issue. The game got updated again and now I can't open BepInEx even with no plugins installed I get this error:
```
[Error  :   BepInEx] System.NullReferenceException: Couldn't find System.Type for Il2Cpp type: System.
   at Il2CppInterop.Runtime.Injection.ClassInjector.SystemTypeFromIl2CppType(Il2CppTypeStruct* typePointer) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 1144
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 432
```

**Comment by akchama** [comment]
@Kasuromi Do you have an educated guest why this might happen?

**Comment by ITR13** [comment]
Might be related to BepInEx/Il2CppInterop#135
