### ISSUE TITLE
Failed to generate Il2Cpp interop assemblies (VRising)

### ISSUE THREAD

**Issue by Stroichik** [BepInEx/BepInEx#866]
### What happened?

install BepInEx from Thunderstore
Try launching game
get red errors in console during load, and game doesn't load.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.668 - VRising
[Message: Preloader] Built from commit 46e297f210c27e9b4d26e7cd326625b53c83faa0
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Info   :    Cpp2IL] [Library] Using actual IL2CPP Metadata version 29,1
[Info   :    Cpp2IL] [Library] Initialized Metadata in 244ms
[Info   :    Cpp2IL] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info   :    Cpp2IL] [Library] Searching Binary for Required Data...
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.Exception: Failed to find Binary code or metadata registration
   at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlBinaryRegistry.cs:line 71
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 159
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 203
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 61
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 67
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.RunCpp2Il() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 278
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.GenerateInteropAssemblies() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 213
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
```

### Environment

```markdown
- OS: Win 10
- BepInEx: 6.0.0-be.668
- Game: VRising
```

**Comment by NeonOby** [comment]
I have the same error with the same method and versions of BepInEx and VRising 1.0!
Maybe the Error Log also helps:
`
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc)
`

**Comment by mossyblog** [comment]
Even if you do manage to get past this error, It has to do with type registrations as near as i can tell - ClassInjector.RegisterTypeInIl2Cpp will immediately trigger a crash. Given even other projects like UnityExplorer fall victim to the same thing.

**Comment by demonkid13579** [comment]
well the game has updated to 1.0 may 8th so might be out of date

**Comment by Marinxar** [comment]
Definitely the update. Just got to hope they get time to update soon ^^

**Comment by das-eisen** [comment]
Same shit. I've been looking for a solution for two hours, but I haven't found anything (

**Comment by NeonOby** [comment]
The solution is to either wait for the VRising Community to fix BepInEx and the mods you want Or to help them if you are a programmer that can. 
Search for "vrising mods wiki" should be the first link, there is a discord and pages about the 1.0 update.

Anyway this also seems to be a problem with BepInEx which is not updated for the latest Games build with Unity. 
So this probably will happen with more games in the future if BepInEx isn't updated.

**Comment by jobsidi** [comment]
Client crashed at the start too:
`
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.Exception: Failed to find Binary code or metadata registration
`
Tried both IL2CPP or mono from latest bleeding edge builds from
https://builds.bepinex.dev/projects/bepinex_be
no results

**Comment by NeonOby** [comment]
The current status is here:
https://wiki.vrisingmods.com/user/game_update
BepInEx and some mods are WIP
