### ISSUE TITLE
Mods not loading V Rising

### ISSUE THREAD

**Issue by Faabyy** [BepInEx/BepInEx#885]
### What happened?

I managed to get my hands on a working Version of BepInEx from Github. Now it seems like any Plugins i try to use, wont work. Is this a problem related with BepInEx?

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 5 plugins to load
[Info   :   BepInEx] Loading [VampireCommandFramework 0.8.2]
[Message:VampireCommandFramework] Note: Vampire Command Framework is loading on the client but only adds functionality on the server at this time, seeing this message is not a problem or bug.
[Info   :   BepInEx] Loading [Bloodstone 0.1.6]
[Error  :Bloodstone] Error loading keybindings, using defaults:
[Error  :Bloodstone] System.TypeInitializationException: The type initializer for 'Bloodstone.API.KeybindManager' threw an exception.
 ---> System.TypeLoadException: Could not load type 'ProjectM.InputFlag' from assembly 'ProjectM.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Bloodstone.API.KeybindManager..cctor()
   --- End of inner exception stack trace ---
   at Bloodstone.API.KeybindManager.Load()
[Error  :   BepInEx] Error loading [Bloodstone 0.1.6]: System.TypeInitializationException: The type initializer for 'Bloodstone.API.KeybindManager' threw an exception.
 ---> System.TypeLoadException: Could not load type 'ProjectM.InputFlag' from assembly 'ProjectM.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Bloodstone.API.KeybindManager..cctor()
   --- End of inner exception stack trace ---
   at Bloodstone.API.KeybindManager.Load()
   at Bloodstone.BloodstonePlugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 134
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
[Warning:   BepInEx] Skipping [CoffinSleep 2.0.1] because it has a dependency that was not loaded. See previous errors for details.
[Info   :   BepInEx] Loading [Silkworm 2.0.0]
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Silkworm, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at HarmonyLib.AccessTools.GetTypesFromAssembly(Assembly assembly)
System.TypeLoadException: Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
[Warning:  Silkworm] Error saving options.json
[Info   :  Silkworm] Plugin iZastic.Silkworm v2.0.0 is loaded!
[Info   :   BepInEx] Loading [ModernCamera 1.5.6]
[Error  :   BepInEx] Error loading [ModernCamera 1.5.6]: System.TypeLoadException: Could not load type 'Il2CppSystem.Nullable_Unboxed`1' from assembly 'Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ModernCamera.Settings.SetupOptions()
   at ModernCamera.Settings.Init()
   at ModernCamera.Plugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 134
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 6.0.0-be.691
- Game: V Rising
```

**Comment by Kasuromi** [comment]
The V-Rising modding community uses a fork of Il2CppInterop that allows for better work with DOTS. Plugins that are built for their fork will not work with upstream Il2CppInterop.

**Comment by Faabyy** [comment]
Is there a way to make these mods work?
