### ISSUE TITLE
BepInEx failing to fully initialise itself (V Rising)

### ISSUE THREAD

**Issue by NotMrFlibble** [BepInEx/BepInEx#987]
### What happened?

Backtraces showing up in the log console. No crash; game starts up unmodified.

(Running via Proton 9.0.)

### Steps to reproduce

Install BepInEx via r2modman or manually (doesn't matter). Launch game with mods (in this case, just BepInEx). Watch as BepInEx throws errors then the game starts up, unmodded.

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.691 - VRising
[Message: Preloader] Built from commit 3ba398f269961fe6721f918423df399d0b481d7e
[Info   :   BepInEx] System platform: Windows 10 (Wine 9.0) 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Info   :    Cpp2IL] [Library] Using actual IL2CPP Metadata version 29.1
[Info   :    Cpp2IL] [Library] Initialized Metadata in 526ms
[Info   :    Cpp2IL] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info   :    Cpp2IL] [Library] Searching Binary for Required Data...
[Info   :    Cpp2IL] [Library] Got Binary codereg: 0x1892CF180, metareg: 0x18B28CDE0 in 737ms.
[Info   :    Cpp2IL] [Library] Initializing Binary...
[Info   :    Cpp2IL] [Library] Initialized Binary in 586ms
[Info   :    Cpp2IL] [Library] Mapping pointers to Il2CppMethodDefinitions...
[Info   :    Cpp2IL] [Library] Processed 212504 OK (181ms)
[Info   :    Cpp2IL] [Program] Creating application model...
[Info   :    Cpp2IL] [Program] Application model created in 7842.3236ms
[Info   :InteropManager] Cpp2IL finished in 00:00:22.6617165
[Info   :InteropManager] Generating interop assemblies
[Info   :Il2CppInteropGen] Reading assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0857799
[Info   :Il2CppInteropGen] Reading unity assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0255154
[Info   :Il2CppInteropGen] Creating rewrite assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0187101
[Info   :Il2CppInteropGen] Computing renames...
[Info   :Il2CppInteropGen] Done in 00:00:00.1226468
[Info   :Il2CppInteropGen] Creating typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.1612444
[Info   :Il2CppInteropGen] Computing generic parameter usage...
[Info   :Il2CppInteropGen] Done in 00:00:00.1336803
[Info   :Il2CppInteropGen] Computing struct blittability...
[Info   :Il2CppInteropGen] Done in 00:00:01.0876622
[Info   :Il2CppInteropGen] Creating unboxed struct types...
[Info   :Il2CppInteropGen] Done in 00:00:00.0014143
[Info   :Il2CppInteropGen] Filling typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.2433632
[Info   :Il2CppInteropGen] Filling generic constraints...
[Info   :Il2CppInteropGen] Done in 00:00:00.0042712
[Info   :Il2CppInteropGen] Creating members...
[Info   :Il2CppInteropGen] Done in 00:00:02.8083999
[Info   :Il2CppInteropGen] Scanning method cross-references...
[Info   :Il2CppInteropGen] Done in 00:00:02.2123773
[Info   :Il2CppInteropGen] Finalizing method declarations...
[Info   :Il2CppInteropGen] Done in 00:00:04.6332570
[Info   :Il2CppInteropGen] 2241 total potentially dead methods
[Info   :Il2CppInteropGen] Filling method parameters...
[Info   :Il2CppInteropGen] Done in 00:00:01.0057390
[Info   :Il2CppInteropGen] Creating static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:01.3682292
[Info   :Il2CppInteropGen] Creating value type fields...
[Info   :Il2CppInteropGen] Done in 00:00:00.4240807
[Info   :Il2CppInteropGen] Creating enums...
[Info   :Il2CppInteropGen] Done in 00:00:00.0854011
[Info   :Il2CppInteropGen] Creating IntPtr constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.3615150
[Info   :Il2CppInteropGen] Creating non-blittable struct constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0371671
[Info   :Il2CppInteropGen] Creating generic method static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.1805027
[Info   :Il2CppInteropGen] Creating field accessors...
[Info   :Il2CppInteropGen] Done in 00:00:01.8156905
[Info   :Il2CppInteropGen] Filling methods...
[Info   :Il2CppInteropGen] Done in 00:00:04.7898098
[Info   :Il2CppInteropGen] Generating implicit conversions...
[Info   :Il2CppInteropGen] Done in 00:00:00.0280754
[Info   :Il2CppInteropGen] Creating properties...
[Info   :Il2CppInteropGen] Done in 00:00:00.1768476
[Info   :Il2CppInteropGen] Unstripping types...
[Info   :Il2CppInteropGen] Done in 00:00:00.0601922
[Info   :Il2CppInteropGen] Unstripping fields...
[Info   :Il2CppInteropGen] Restored 397 fields
[Info   :Il2CppInteropGen] Failed to restore 0 fields
[Info   :Il2CppInteropGen] Done in 00:00:00.0106900
[Info   :Il2CppInteropGen] Unstripping methods...
[Info   :Il2CppInteropGen] Restored 15611 methods
[Info   :Il2CppInteropGen] Failed to restore 910 methods
[Info   :Il2CppInteropGen] Done in 00:00:00.4600759
[Info   :Il2CppInteropGen] Unstripping method bodies...
[Info   :Il2CppInteropGen] IL unstrip statistics: 7999 successful, 1836 failed
[Info   :Il2CppInteropGen] Done in 00:00:00.5861252
[Info   :Il2CppInteropGen] Writing xref cache...
[Info   :Il2CppInteropGen] Done in 00:00:03.7446381
[Info   :Il2CppInteropGen] Writing assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:01.4639527
[Info   :Il2CppInteropGen] Writing method pointer map...
[Info   :Il2CppInteropGen] Done in 00:00:00.1112306
[Info   :Il2CppInteropGen] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.TypeInitializationException: The type initializer for 'Il2CppInterop.Runtime.Injection.InjectorHelpers' threw an exception.
 ---> System.ComponentModel.Win32Exception (31): General failure.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.Process.get_Modules()
   at Il2CppInterop.Runtime.Injection.InjectorHelpers..cctor() in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\InjectorHelpers.cs:line 30
   --- End of inner exception stack trace ---
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\InjectorHelpers.cs:line 74
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\ClassInjector.cs:line 203
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\ClassInjector.cs:line 159
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp[T]() in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\ClassInjector.cs:line 154
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\DelegateSupport.cs:line 244
   at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 104
[Fatal  :   BepInEx] Unable to execute IL2CPP chainloader
[Error  :   BepInEx] System.TypeInitializationException: The type initializer for 'Il2CppInterop.Runtime.Injection.InjectorHelpers' threw an exception.
 ---> System.ComponentModel.Win32Exception (31): General failure.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.Process.get_Modules()
   at Il2CppInterop.Runtime.Injection.InjectorHelpers..cctor() in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\InjectorHelpers.cs:line 30
   --- End of inner exception stack trace ---
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\InjectorHelpers.cs:line 74
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\ClassInjector.cs:line 203
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\ClassInjector.cs:line 159
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp[T]() in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Injection\ClassInjector.cs:line 154
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\DelegateSupport.cs:line 244
   at UnityEngine.Application.LogCallback.op_Implicit(Action`3 )
   at BepInEx.Unity.IL2CPP.Logging.IL2CPPUnityLogSource..ctor() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Logging/IL2CPPUnityLogSource.cs:line 11
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 104
```

### Environment

```markdown
- OS: Devuan daedalus
- BepInEx: 6.0.0-be.691
- Game: V Rising
```

**Comment by NotMrFlibble** [comment]
I also tested be.716; no difference, other than having to fix up file permissions as part of installation.

**Comment by karaok1** [comment]
I have same problem with another game. Is there at least a temporary solution for this?

**Comment by BonnieBoestar** [comment]
Having the exact same problem with Shadows of Doubt, "Unable to execute IL2CPP chainloader". Do you happen to be using r2modman or Thunderstore?
